# Generated by Django 6.0 on 2025-12-28 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
